permalink: pretty
auto: true
pygments: true

# Theme settings
theme:

  # Site name
  site_name: acusti.ca
  
  # Site base URL
  base_url: acusti.ca
  # base_url: 0.0.0.0:4000
  # base_url: dl-web.dropbox.com/spa/66k6nlg4jn687wm/acusti/public/github/_site
  
  # Google analytics UID
  google_analytics_uid: UA-28481823-1
  
  # Disqus shortname, for comments
  disqus_shortname: acusti-github
  
  # Number of featured posts on homepage
  homepage_featured: 2
  
  # Number of posts on homepage (in addition to featured posts)
  homepage_posts: 3
  
  # Number of words to display in post summaries
  featured_wordcount: 30