permalink: pretty
auto: true

# Theme settings
theme:

  # Site name
  site_name: acusti.ca
  
  # Site base URL
  base_url: acusti.github.com

  # Google analytics UID
  google_analytics_uid: UA-28481823-1

  # Disqus shortname, for comments
  disqus_shortname: acusti-github

  # Number of featured posts on homepage
  homepage_featured: 2

  # Number of posts on homepage (in addition to featured posts)
  homepage_posts: 3

  # Number of words to display in post summaries
  featured_wordcount: 30